version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: reeble-backend
    ports:
      - "8000:8000"
    environment:
      - ANVIL_API_KEY=${ANVIL_API_KEY:-your-anvil-api-key}
      - ANVIL_ORG_EID=${ANVIL_ORG_EID:-your-anvil-org-eid}
      - PDF_STORAGE_PATH=${PDF_STORAGE_PATH:-your-storage-path}
    volumes:
      - ./backend/upload:/app/upload
      - backend_data:/app
    networks:
      - reeble-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8000
    container_name: reeble-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - reeble-network
    restart: unless-stopped

volumes:
  backend_data:

networks:
  reeble-network:
    driver: bridge 