version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: reeble-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - SECRET_KEY=your-secret-key-here
      - ANVIL_API_KEY=${ANVIL_API_KEY:-your-anvil-api-key}
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - ./backend/upload:/app/upload
      - backend_data:/app
    networks:
      - reeble-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reeble-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - reeble-network
    restart: unless-stopped

volumes:
  backend_data:

networks:
  reeble-network:
    driver: bridge 